### PR TITLE
5829 support unicode in packing list file name

### LINKED ISSUE #5829: Handle unicode characters when generating file names
Relates to: https://pihemr.atlassian.net/browse/OBS-1960

When generating file names, we usually base it off things like shipment or order name. When those fields have a unicode character (which can easily happen when working with non-english characters), we get the following error:
```
The HTTP response header [Content-disposition] with value [attachment; filename="Packing List - McKessonMedicalSurgical-VentureMiamiWarehouse:UGHEStock-09Mar2026-INTPO013022UGHE(UrgentAir)-Mobilesimcartproject​McKessonIOPS-19295.xls"] has been removed from the response because it is invalid
java.lang.IllegalArgumentException: The Unicode character [​] at code point [8,203] cannot be encoded as it is outside the permitted range of 0 to 255
```

We need to change how we generate the content-disposition header so that it allows for unicode characters. There's a standard approach to this. Something like:
```
String filename = "abc.xls"
String filenameUTF8 = URLEncoder.encode(filename, StandardCharsets.UTF_8.name())

response.setHeader("Content-disposition", "attachment; filename=\"${filename}\"; filename*=UTF-8''${filenameUTF8}")
```

The above OBS ticket relates to the logic in `Doc4jController.downloadPackingList()` but we should aim to fix this across all the places that we set the content-disposition header. Likely having some util class for this will be the way to go

### PR DESCRIPTION
**Pull request by ewaterman**
### :sparkles: Description of Change

[//]: <> (A concise summary of what is being changed. Please provide enough context for reviewers to be able to understand the change and why it is necessary.)

**Link to GitHub issue or Jira ticket:** fixes https://github.com/openboxes/openboxes/issues/5829

**Description:** Support unicode characters when generating the file name for a packing list.

### CODE REVIEW

File: src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import org.springframework.http.HttpHeaders
+import org.springframework.stereotype.Component
+
+import org.pih.warehouse.core.file.FileNameGenerator
+
+/**
+ * Wraps HttpServletResponse instances, configuring them for use in HTTP responses.
+ */
+@Component
+class HttpServletResponseConfigurer {
```
Comment (ewaterman) [inline src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy:15]: Adding this class wasn't necessary to the change, but wrapping the response like this will help to standardize and abstract away how we set fields on the response. I eventually want to refactor all file export flows to use this approach.

**Comment by jmiranda** [comment]
@ewaterman You crazy.  In a good way :)

File: grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy [hunk 2]
```diff
@@ -10,12 +10,16 @@
...
+
+import org.pih.warehouse.core.http.ContentType
+import org.pih.warehouse.core.http.HttpServletResponseConfigurer
 import org.pih.warehouse.shipping.Shipment
 
 @Transactional
 class Doc4jController {
 
     def documentService
+    HttpServletResponseConfigurer httpServletResponseConfigurer
```
Comment (jmiranda) [inline grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy:22]: How does this get initialized? I was expecting to see it in resources.groovy?

File: src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+                case String:
+                    fileName += field.trim()
+                    break
+                default:
+                    fileName += field.toString().trim()
+                    break
+            }
+
+            if (iterator.hasNext()) {
+                fileName += FIELD_DELIMITER
```
Comment (jmiranda) [inline src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy]: Pass this in as an argument to the method. 
```
String generate(FileType fileType, Collection<Object> fields, String delimiter = FIELD_DELIMITER) { 
    ... 
}
```
You could also do it like this
```
String generate(FileType fileType, Collection<Object> fields) { 
    generate(fileType, fields, FIELD_DELIMITER)
}
```
I'd also recommend renaming it and moving it to Constants. Something like Constants.FILENAME_PART_SEPARATOR.

File: grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy (hunk 2 above)
Comment (jmiranda) [reply grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy:22]: Nevermind, I see the Component annontation now.

File: src/main/groovy/org/pih/warehouse/core/file/FileType.groovy [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+ * Enumerates the file types that we operate on within the application.
+ */
+enum FileType {
+
+    NONE(""),
+    CSV(".csv"),
+    JSON(".json"),
+    PDF(".pdf"),
+    XLS(".xls"),
+    XLSX(".xlsx")
```
Comment (jmiranda) [inline src/main/groovy/org/pih/warehouse/core/file/FileType.groovy]: I feel like we're missing a bunch (DOC, DOCX, HTML, XML, TXT, etc). We might not use them all yet, but we should try to incorporate as many of the most common ones so developers don't have to second-guess if they ever need to generate . Would we or do we ever need to use this for images? If so we have a bunch more there. 

If this gets used in the DocumentController where we can upload and download any file type then we might have to rethink this. Although in that case, we use the uploaded filename. But as a thought experiment. If we need to rewrite the filename, the document will have the extension and content type as a string, so we just need to make sure your methods allow for either a conversion to enum or they take a string instead of enum.

Comment (jmiranda) [reply src/main/groovy/org/pih/warehouse/core/file/FileType.groovy]: This is just a FileExtension enum, not a file type. FileType is more like spreadsheet, document, image, etc.

File: src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+/**
+ * Enumerates the HTTP content types that we operate on within the application.
+ */
+enum ContentType {
+
+    CSV("text/csv", FileType.CSV),
+    JSON("application/json", FileType.JSON),
+    PDF("application/pdf", FileType.PDF),
+    XLS("application/vnd.ms-excel", FileType.XLS),
+    XLSX("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", FileType.XLSX)
```
Comment (jmiranda) [inline src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy]: I feel like we should be using a standard library for the content type (Spring's MediaType?). In fact, maybe we could get to a place where we just need one enum for the file or export format and that wraps the spring MediaType?

Something like
```
enum ExportFormat {
    CSV(FileType.CSV, MediaType.parseMediaType("text/csv")),
    JSON(FileType.JSON, MediaType.APPLICATION_JSON),
    XLS(FileType.XLS, MediaType.parseMediaType("application/vnd.ms-excel")),
    ...

    String extension
    MediaType 
```

The question is whether we actually need FileType. I think we could just replace it with the extension string 
```
CSV(".csv", MediaType.parseMediaType("text/csv")),
```

We could go way overboard and find a library that handles the mimetype to extension mapping. This SO article suggests it's possible https://stackoverflow.com/questions/48053127/get-the-extension-from-a-mimetype using jodd-util (?) https://mvnrepository.com/artifact/org.jodd/jodd-util
```
MimeTypeMap.getSingleton().getExtensionFromMimeType(mimType)
```
but that does not seem like a good use of time.

File: src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy (hunk 1 above)
Comment (jmiranda) [reply src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy:15]: +1 except for the name. 

Maybe we could name it something more descriptive 
* FileDownloadResponseBuilder 
* FileDownloadResponseConfigurer
* FileExportResponseBuilder 
* FileExportResponseHelper

File: src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy (hunk 3 above)
Comment (jmiranda) [reply src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy]: Also, appending the field separator happens without regard for the next field. Could we move this up after the null check to make sure it only happens when we likely have a field to display.

File: src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+    /**
+     * Generates a file name for the given file type using the given fields.
+     */
+    String generate(FileType fileType, Collection<Object> fields) {
+        String fileName = ""
+
+        Iterator<Object> iterator = fields.iterator()
+        while(iterator.hasNext()) {
+            Object field = iterator.next()
+            if (!field) {
```
Comment (jmiranda) [inline src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy]: What does this catch? 
* null
* ""
* "    "
* 0
* false

File: src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy (hunk 5 above)
Comment (jmiranda) [reply src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy]: Also, I don't see DOC and DOCX. I know we generate either a DOC or DOCX somewhere in the code.

File: grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy (hunk 2 above)
Comment (ewaterman) [reply grails-app/controllers/org/pih/warehouse/core/Doc4jController.groovy:22]: in case you were curious, the Component annotation works because of this https://github.com/openboxes/openboxes/blob/251fb259d7907d516c9197ae7843476eacc1053c/grails-app/init/org/pih/warehouse/Application.groovy#L12

File: src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy (hunk 6 above)
Comment (ewaterman) [reply src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy]: it catches anything falsy. null, empty strings (but not blank ones), 0, false.

I suppose it's imperfect so I'll try to rethink it

File: src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy (hunk 1 above)
Comment (ewaterman) [reply src/main/groovy/org/pih/warehouse/core/http/HttpServletResponseConfigurer.groovy:15]: my hope is that this is not restricted to just exports. I'd love for this to be used whenever we need to operate on the response.

I originally had it named *Builder but changed to *Configurer because the response already exists and we're just operating on it

File: src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy (hunk 5 above)
Comment (ewaterman) [reply src/main/groovy/org/pih/warehouse/core/http/ContentType.groovy]: oh awesome I was looking for a mimetype/mediatype enum or const to use for this but couldn't find a good one. Spring's MediaType looks like what I needed.

I kept FileType separate because I thought it might be useful more broadly outside of the context of just HTTP requests. I could merge them but I do like the flexibility of having it for other use cases though I can't think of any off the top of my head)

File: src/main/groovy/org/pih/warehouse/core/file/FileType.groovy (hunk 4 above)
Comment (ewaterman) [reply src/main/groovy/org/pih/warehouse/core/file/FileType.groovy]: this wasn't meant to be an exhaustive list, at least initially, but I take your point. I can add your suggested ones now.

and yes I can add a fromExtension(String extension) method here for that use case

File: src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy (hunk 3 above)
Comment (ewaterman) [reply src/main/groovy/org/pih/warehouse/core/file/FileNameGenerator.groovy]: I'll do the first suggestion.

Yes good point I can rework this method a bit to make it smarter. If a field is made blank after parsing we don't want to include the separator

**Comment by ewaterman** [comment]
I'm merging so that we can get it to QA as Kelsey is hoping we have time to fit this in the release but as always we can continue the discussion
